name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Trabalho Individual CI
      working-directory: ./Trabalho-GCS-Individual
      run: docker-compose up -d
